### ISSUE TITLE
Clean up the repository

### ISSUE THREAD

**Issue by ProgramCrafter** [ProgramCrafter/totp-uefi#1]
Currently submodules' versions are not updated to reflect that they were fixed for no_std environment, there is no README, etc.

**Comment by Aydin62** [comment]
Hi. I'm a beginner in Rust but I love it so much! Do you think I might be qualified enough to handle this issue?

**Comment by ProgramCrafter** [comment]
Hi @Aydin62! I believe yes; this is mostly a non-code contribution.

**Comment by Aydin62** [comment]
Very well. So, may I be assigned to this task, please?

**Comment by ProgramCrafter** [comment]
Could you estimate the time for completing the issue, please?

**Comment by Aydin62** [comment]
OK, but a question first: are there any other tasks pending the completion of this one (so that you may need this sooner), or can I take my time for TSC5 and then focus on this one?

**Comment by ProgramCrafter** [comment]
Actually, this is a separate project (it's even not part of Hack-TON-berfest). No, there are no tasks blocked on this one.

**Comment by Aydin62** [comment]
Great! So, please let me get a bit more familiar with the project, and to participate in TSC5. Then, sometime around Sat, Oct 07 I will give you my time estimate. Is this OK for you?

**Comment by ProgramCrafter** [comment]
Do you mean TON Tact Challenge or NFT Standard Challenge? I see no TSC5 running.
Other than that, OK

**Comment by Aydin62** [comment]
Tact Challenge. 
Mistakenly supposed it being TSC5! 😅

**Comment by Aydin62** [comment]
Hi @ProgramCrafter! I guess I can accomplish this task in about 4 days. Just some questions:

1. Concerning the submodule version updates, and to follow SemVer rules, I suppose the shift from ```std``` to ```no-std``` should be regarded as a major version increment; do you confirm this?

2. Also, I'd like to know if such updates are to be published on <em>crates.io</em> or not. If yes, then I'm OK with the above SemVer updates. However, if these updates are to be specific to the current project only, then it is unclear for me how to avoid future version clashes with the official published crates. Could you clarify this issue, please?

3. Within the README file, are there any particular items to be included, apart from general descriptions of the dependencies, links, licenses,  etc.?

4. Finally, are you considering any other cleanups to be done?

**Comment by ProgramCrafter** [comment]
1. Shift from `std` to `no-std` could've broken some compatibility with `std` environments, so yes, that is a major version increment according to SemVer. Though,

2. these versions of crates are going to be submitted as PRs to relevant repositories, I think. There is no need to publish them on *crates.io*. Tag `...-patch-nostd-pc` can be added in order to avoid name clashes.

3. A program description, capabilities and screenshot can be added:
> This is a TOTP implementation that is compiled into single EFI file, that can be launched on a computer or in virtual machine. Thus, it can be launched without an operating system.
> Its other features are:
> 1. Different key lengths are supported.
> 2. Code is generated and updated instantly.
> 3. Key is preserved across reboots (you can use build from commit 20f545d if you don't want this).

![изображение](https://github.com/ProgramCrafter/totp-uefi/assets/82749242/7e381149-bfae-4769-911c-9b3d5d9c5cec)

4. I don't remember any other cleanup that should be done.

**Comment by Aydin62** [comment]
About ```Cargo.toml``` files:

1. I noticed the main Cargo file is edition 2021 edition. Is this correct, or should I change it to 2023? 

2. Also, am I correct that I have to set the editions of all the submodule Cargo files equal to the main Cargo as well?

3. I couldn't find any reference to the ```crypto-commons``` submodule in any of the Cargo files. I'm wondering if this is OK or not.

**Comment by ProgramCrafter** [comment]
1. It is correct; there is no 2023 [Rust edition](https://doc.rust-lang.org/stable/edition-guide/editions/index.html).
2. I think there is no need to do so, as that would force crate maintainers to use the new edition.
3. Indeed, it can be removed.

**Comment by Aydin62** [comment]
Finished my work and created a PR.
